# Generated by Django 5.0.2 on 2024-05-14 08:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Review_Web',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('rating', models.IntegerField(blank=True, default=0, null=True, verbose_name='Sao')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Nội dung đánh giá')),
                ('createdAt', models.DateTimeField(auto_now_add=True, verbose_name='Ngày đánh giá')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Người dùng')),
            ],
            options={
                'verbose_name_plural': ' Quản lý Đánh giá Website',
            },
        ),
    ]
