# Generated by Django 5.0.2 on 2024-05-14 03:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chapter', '0004_alter_chapter_content'),
        ('novel', '0006_alter_novel_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chapter',
            options={'verbose_name': 'Quản lý chương', 'verbose_name_plural': 'Các chương'},
        ),
        migrations.AlterField(
            model_name='chapter',
            name='content',
            field=models.FileField(null=True, upload_to='Content', verbose_name='Nội dung'),
        ),
        migrations.AlterField(
            model_name='chapter',
            name='createdAt',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo'),
        ),
        migrations.AlterField(
            model_name='chapter',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Tên chương'),
        ),
        migrations.AlterField(
            model_name='chapter',
            name='novel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='novel.novel', verbose_name='Tiểu thuyết'),
        ),
        migrations.AlterField(
            model_name='chapter',
            name='number',
            field=models.IntegerField(blank=True, null=True, verbose_name='Chương số'),
        ),
        migrations.AlterField(
            model_name='chapter',
            name='views',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Lượt xem'),
        ),
    ]
