# Generated by Django 5.0.2 on 2024-05-14 04:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chapter', '0005_alter_chapter_options_alter_chapter_content_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chapter',
            options={'verbose_name': 'Quản lý chương', 'verbose_name_plural': 'Quản lý chương'},
        ),
    ]
