# Generated by Django 5.0.2 on 2024-05-14 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genres', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={'verbose_name': 'Quản lý tác giả', 'verbose_name_plural': 'Quản lý tác giả'},
        ),
        migrations.AlterModelOptions(
            name='genres',
            options={'verbose_name': 'Quản lý thể loại', 'verbose_name_plural': 'Quản lý thể loại'},
        ),
        migrations.AlterField(
            model_name='author',
            name='createdAt',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo'),
        ),
        migrations.AlterField(
            model_name='author',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Tên tác giả'),
        ),
        migrations.AlterField(
            model_name='genres',
            name='createdAt',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo'),
        ),
        migrations.AlterField(
            model_name='genres',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Mô tả'),
        ),
        migrations.AlterField(
            model_name='genres',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Tên thể loại'),
        ),
    ]
