# Generated by Django 5.0.2 on 2024-05-14 04:17

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0002_usercustom_birth_usercustom_gender'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usercustom',
            options={'verbose_name': 'Quản lý người dùng', 'verbose_name_plural': 'Quản lý Người dùng'},
        ),
        migrations.AlterField(
            model_name='role',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Tên quyền'),
        ),
        migrations.AlterField(
            model_name='usercustom',
            name='address',
            field=models.CharField(default=None, max_length=50, null=True, verbose_name='Địa chỉ'),
        ),
        migrations.AlterField(
            model_name='usercustom',
            name='birth',
            field=models.DateField(null=True, verbose_name='Ngày sinh'),
        ),
        migrations.AlterField(
            model_name='usercustom',
            name='date_joined',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Ngày đăng ký'),
        ),
        migrations.AlterField(
            model_name='usercustom',
            name='fullname',
            field=models.CharField(default=None, max_length=50, null=True, verbose_name='Họ và tên'),
        ),
        migrations.AlterField(
            model_name='usercustom',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Nam'), ('female', 'Nữ')], max_length=200, null=True, verbose_name='Giới tính'),
        ),
        migrations.AlterField(
            model_name='usercustom',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Kích hoạt'),
        ),
        migrations.AlterField(
            model_name='usercustom',
            name='phone_number',
            field=models.IntegerField(default=None, null=True, verbose_name='SĐT'),
        ),
        migrations.AlterField(
            model_name='usercustom',
            name='role_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Auth.role', verbose_name='Loại tài khoản'),
        ),
    ]
