# Generated by Django 5.0.2 on 2024-05-14 03:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genres', '0001_initial'),
        ('novel', '0003_novel_features_alter_novel_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='novel',
            options={'verbose_name': 'Tiểu thuyết', 'verbose_name_plural': 'Các Tiểu thuyết'},
        ),
        migrations.AlterField(
            model_name='novel',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='genres.author', verbose_name='Tác giả'),
        ),
        migrations.AlterField(
            model_name='novel',
            name='createdAt',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo'),
        ),
        migrations.AlterField(
            model_name='novel',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Mô tả'),
        ),
        migrations.AlterField(
            model_name='novel',
            name='features',
            field=models.CharField(blank=True, choices=[('hot', 'Hot'), ('new', 'New'), ('full', 'Full')], max_length=200, null=True, verbose_name='Đặc trưng'),
        ),
        migrations.AlterField(
            model_name='novel',
            name='genres',
            field=models.ManyToManyField(blank=True, related_name='manga_genres', to='genres.genres', verbose_name='Thể loại'),
        ),
        migrations.AlterField(
            model_name='novel',
            name='image',
            field=models.FileField(blank=True, default='/Novel/default.png', null=True, upload_to='Novel', verbose_name='Ảnh'),
        ),
        migrations.AlterField(
            model_name='novel',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Tên tiểu thuyết'),
        ),
        migrations.AlterField(
            model_name='novel',
            name='numReviews',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Tổng lượt đánh giá'),
        ),
        migrations.AlterField(
            model_name='novel',
            name='rating',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Đánh giá'),
        ),
        migrations.AlterField(
            model_name='novel',
            name='status',
            field=models.CharField(blank=True, choices=[('continue', 'tiếp tục'), ('stoped', 'Đã dừng lại'), ('complete', 'Hoàn thành')], max_length=200, null=True, verbose_name='Trạng thái'),
        ),
        migrations.AlterField(
            model_name='novel',
            name='updatedAt',
            field=models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật'),
        ),
        migrations.AlterField(
            model_name='novel',
            name='views',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Lượt xem'),
        ),
    ]
