# Generated by Django 5.0.2 on 2024-05-14 03:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('novel', '0004_alter_novel_options_alter_novel_author_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='novel',
            options={'verbose_name': 'Quản lý Tiểu thuyết', 'verbose_name_plural': 'Các Tiểu thuyết'},
        ),
    ]
