# Generated by Django 5.0.2 on 2024-05-14 03:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('novel', '0005_alter_novel_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='novel',
            options={'verbose_name': 'Tiểu thuyết', 'verbose_name_plural': 'Các Tiểu thuyết'},
        ),
    ]
