# Generated by Django 5.0.2 on 2024-05-14 04:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novel', '0006_alter_novel_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='novel',
            options={'verbose_name': 'Tiểu thuyết', 'verbose_name_plural': ' Quản lý Tiểu thuyết'},
        ),
        migrations.AlterModelOptions(
            name='review',
            options={'verbose_name_plural': ' Quản lý Đánh giá tiểu thuyết'},
        ),
        migrations.RemoveField(
            model_name='review',
            name='name',
        ),
        migrations.AlterField(
            model_name='review',
            name='comment',
            field=models.TextField(blank=True, null=True, verbose_name='Lời đánh giá'),
        ),
        migrations.AlterField(
            model_name='review',
            name='createdAt',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Ngày đánh giá'),
        ),
        migrations.AlterField(
            model_name='review',
            name='novel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='novel.novel', verbose_name='Tiểu thuyết'),
        ),
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Sao'),
        ),
        migrations.AlterField(
            model_name='review',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Người dùng'),
        ),
    ]
