# Generated by Django 5.0.2 on 2024-05-14 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novel', '0007_alter_novel_options_alter_review_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='comment',
            field=models.TextField(blank=True, null=True, verbose_name='Nội dung đánh giá'),
        ),
    ]
