# Generated by Django 5.0.2 on 2024-05-15 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novel', '0009_readinghistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='novel',
            name='image',
            field=models.ImageField(blank=True, default='/Novel/default.png', null=True, upload_to='Novel', verbose_name='Ảnh'),
        ),
    ]
